// ============================================================================
// 16-bit Arbiter-PUF timing-path prototype (v3)
//
// Purpose:
//   - Provide a synthesis-oriented 16-stage switch-box cascade matching the
//     behavioral 16-bit PUF used for the experimental dataset.
//   - Expose both race endpoints for post-place-and-route timing inspection.
//
// Important methodological boundary:
//   A zero-delay RTL simulator cannot establish which racing path wins, and a
//   generic synthesizable always block cannot reproduce FPGA routing delay.
//   Therefore this file is a timing-path prototype, not the source of the
//   numerical dataset. The response used in the paper is generated by the
//   independent behavioral physical model in generate_dataset_v3.py. A real
//   hardware claim requires Quartus post-fit timing evidence and measurements
//   from physical DE1-SoC devices.
// ============================================================================

module arbiter_puf_16bit_timing_wrapper #(
    parameter N_BITS = 16
)(
    input  wire             clk_50,
    input  wire             puf_trigger,
    input  wire [N_BITS-1:0] puf_challenge,
    output wire             race_top,
    output wire             race_bottom
);

    (* keep = 1, dont_touch = 1 *) wire [N_BITS-1:0] top_path;
    (* keep = 1, dont_touch = 1 *) wire [N_BITS-1:0] bottom_path;

    genvar i;
    generate
        for (i = 0; i < N_BITS; i = i + 1) begin : G
            if (i == 0) begin : FIRST
                puf_switch_box_v3 u_sb (
                    .in_top    (puf_trigger),
                    .in_bottom (puf_trigger),
                    .challenge (puf_challenge[i]),
                    .out_top   (top_path[i]),
                    .out_bottom(bottom_path[i])
                );
            end else begin : NEXT
                puf_switch_box_v3 u_sb (
                    .in_top    (top_path[i-1]),
                    .in_bottom (bottom_path[i-1]),
                    .challenge (puf_challenge[i]),
                    .out_top   (top_path[i]),
                    .out_bottom(bottom_path[i])
                );
            end
        end
    endgenerate

    assign race_top = top_path[N_BITS-1];
    assign race_bottom = bottom_path[N_BITS-1];
endmodule

module puf_switch_box_v3 (
    input  wire in_top,
    input  wire in_bottom,
    input  wire challenge,
    output wire out_top,
    output wire out_bottom
);
    (* keep = 1, dont_touch = 1 *) wire t0, t1, b0, b1;
    assign t0 = in_top    & ~challenge;
    assign t1 = in_bottom &  challenge;
    assign b0 = in_bottom & ~challenge;
    assign b1 = in_top    &  challenge;
    assign out_top = t0 | t1;
    assign out_bottom = b0 | b1;
endmodule
